apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: first-pod
  ports:
    - port: 80
    #- targetPort: 8080????
      nodePort: 30000